### ISSUE TITLE
401

### ISSUE THREAD

**Issue by jgjc222** [zhuowei/TweetbotLoginProxy#1]
Hi,
running the code returns a 401, the twitter app I have is 8 years old. Should I be creating a new one?

**Comment by zhuowei** [comment]
Did you add the correct callback URL to the app? Did it give any other error?

**Comment by jgjc222** [comment]
Thank you for the quick response.. I will share the logs later, however I was only able to put the callback url with 2 slashes. Here's the error message when I put 3.![image](https://user-images.githubusercontent.com/10481306/213396057-3ceec0f8-fc0a-49a2-aa00-87496205c202.jpeg)

**Comment by zhuowei** [comment]
I have "Type of App" set as "Native App" - does that fix it?

**Comment by jgjc222** [comment]
I don't see it, maybe I'm on the wrong page?![image](https://user-images.githubusercontent.com/10481306/213400584-c8abb015-8cf9-4610-bb07-9671f85c785a.jpeg)

**Comment by zhuowei** [comment]
OK, I guess new projects have a different view. (Maybe you need to turn on "Login with Twitter" or something?) I guess you could point it at some other URL, then use mitmproxy to redirect that URL to the Tweetbot callback URL. I'll take a look at this tomorrow. I'm sorry about this.

**Comment by jgjc222** [comment]
Turning on login with twitter would just make the callback field mandatory, I tried it.
I will also try a different url as you mentioned and share more detailed logs. I appreciate your help. 🙏🏻

**Comment by jgjc222** [comment]
I think the issue was the callback url. I'm not getting errors anymore. However, I'm still trying to figure out how to rewrite the callback URL to tweetbot:///token

**Comment by jgjc222** [comment]
I was able to login after rewriting the callback redirect. I think the my app is really old, explains this error message. Thank you for your help.![image](https://user-images.githubusercontent.com/10481306/213535453-1ddbba13-6e42-4f4d-bebe-a26b5893d170.jpeg)

**Comment by zhuowei** [comment]
Thanks. I have a 2014-era Twitter app that I'll try later this week. If I could figure out how to get that app working properly, I'll add it to the instructions.
